<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFhlifga\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFhlifga/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFhlifga.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFhlifga\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFhlifga\appProdProjectContainer(array(
    'container.build_hash' => 'Fhlifga',
    'container.build_id' => 'c7f06cb4',
    'container.build_time' => 1539106543,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFhlifga');
