<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3962pvv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3962pvv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3962pvv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3962pvv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3962pvv\appDevDebugProjectContainer(array(
    'container.build_hash' => '3962pvv',
    'container.build_id' => '97045eea',
    'container.build_time' => 1546455427,
), __DIR__.\DIRECTORY_SEPARATOR.'Container3962pvv');
