<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN5x3ed4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN5x3ed4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerN5x3ed4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerN5x3ed4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerN5x3ed4\appProdProjectContainer(array(
    'container.build_hash' => 'N5x3ed4',
    'container.build_id' => 'eba1ada0',
    'container.build_time' => 1542056086,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerN5x3ed4');
